/// Flutter icons MyMoodIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyMoodIcon
///      fonts:
///       - asset: fonts/MyMoodIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyMoodIcon {
  MyMoodIcon._();

  static const _kFontFam = 'MyMoodIcon';

  static const IconData chat = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe802, fontFamily: _kFontFam);
}
